### ISSUE TITLE
V4: Postgres extension `tablefunc` causes error

### ISSUE THREAD

**Issue by proehlen** [postgraphql/graphql-build#16]
I love the direction you are taking postgraphql.  It's just what I've been waiting for so thanks for taking it on.  Below is an issue I've come across using the new beta version.

To reproduce, execute the following SQL in a database you are connecting to with postgraphql:
```
CREATE extension IF NOT EXISTS tablefunc;
```
Fire up postgraphql via the CLI tool and you get this error:
```
* * *

Error: Schema query must be Object Type but got: undefined.
    at invariant (/home/peter/Git/test/node_modules/graphql/jsutils/invariant.js:19:11)
    at new GraphQLSchema (/home/peter/Git/test/node_modules/graphql/type/schema.js:72:88)
    at Object.newWithHooks (/home/peter/Git/test/node_modules/graphql-build/src/makeNewBuild.js:466:14)
    at SchemaBuilder.buildSchema (/home/peter/Git/test/node_modules/graphql-build/src/SchemaBuilder.js:164:36)
    at exports.createPostGraphQLSchema (/home/peter/Git/test/node_modules/postgraphql-build/src/index.js:66:18)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:169:7)
```
Debugging the issue, it appears the problem is caused by one or more of these functions that are created by the extension:
![2017-07-22-201517_428x281_scrot](https://user-images.githubusercontent.com/8384068/28491384-9081164c-6f1a-11e7-9dec-11fd8e473835.png)

Specifically the following exception is thrown:

```
Exception has occurred: Error
Error: Can only create NonNull of a Nullable GraphQLType but got: undefined.
    at invariant (/home/peter/Git/test/node_modules/graphql/jsutils/invariant.js:19:11)
    at new GraphQLNonNull (/home/peter/Git/test/node_modules/graphql/type/definition.js:780:84)
    at makeProcField (/home/peter/Git/test/node_modules/graphql-build-pg/src/plugins/makeProcField.js:121:16)
    at introspectionResultsByKind.procedure.filter.reduce (/home/peter/Git/test/node_modules/graphql-build-pg/src/plugins/PgQueryProceduresPlugin.js:62:31)
    at Array.reduce (native)
    at PgQueryProceduresPlugin.builder.hook (/home/peter/Git/test/node_modules/graphql-build-pg/src/plugins/PgQueryProceduresPlugin.js:19:12)
    at SchemaBuilder.applyHooks (/home/peter/Git/test/node_modules/graphql-build/src/SchemaBuilder.js:115:20)
    at fields (/home/peter/Git/test/node_modules/graphql-build/src/makeNewBuild.js:344:40)
    at resolveThunk (/home/peter/Git/test/node_modules/graphql/type/definition.js:169:40)
    at defineFieldMap (/home/peter/Git/test/node_modules/graphql/type/definition.js:350:18)
    at GraphQLObjectType.getFields (/home/peter/Git/test/node_modules/graphql/type/definition.js:311:44)
    at Object.newWithHooks (/home/peter/Git/test/node_modules/graphql-build/src/makeNewBuild.js:469:16)
    at QueryPlugin.builder.hook (/home/peter/Git/test/node_modules/graphql-build/src/plugins/QueryPlugin.js:18:25)
    at SchemaBuilder.applyHooks (/home/peter/Git/test/node_modules/graphql-build/src/SchemaBuilder.js:115:20)
    at Object.newWithHooks (/home/peter/Git/test/node_modules/graphql-build/src/makeNewBuild.js:146:27)
    at SchemaBuilder.buildSchema (/home/peter/Git/test/node_modules/graphql-build/src/SchemaBuilder.js:164:36)
```

Removing the extension removes the problem.

I no longer need the extension so don't have an issue myself but logging it in case you are interested.

**Comment by benjie** [comment]
Thanks for reporting; it'd be super helpful if you could provide a minimal test case where it fails but commenting the extension makes it work; also the PostGraphQL command line you're using for it. Are you specifying a schema to PostGraphQL as things in the public schema can often confuse things; I never use the public schema with PostGraphQL.

**Comment by proehlen** [comment]
Sure, repro here:
https://github.com/proehlen/graphql-build-issue-16-repro

Follow the README but it's just three tiny scripts. 1 and 3 works, 2 breaks it.

**Comment by benjie** [comment]
New error logging here helps:

```
    console.warn node_modules/graphql-build/node8plus/makeNewBuild.js:403
      An error occurred, it might be okay but it doesn't look like the error we were expecting...
    console.warn node_modules/graphql-build/node8plus/makeNewBuild.js:405
      Error: Can only create NonNull of a Nullable GraphQLType but got: undefined.
          at invariant (/Users/benjiegillam/Documents/graphql-build/node_modules/graphql/jsutils/invariant.js:19:11)
          at new GraphQLNonNull (/Users/benjiegillam/Documents/graphql-build/node_modules/graphql/type/definition.js:780:84)
          at makeProcField (/Users/benjiegillam/Documents/graphql-build/packages/postgraphql-build/node_modules/graphql-build-pg/node8plus/plugins/makeProcField.js:132:16)
          at introspectionResultsByKind.procedure.filter.reduce (/Users/benjiegillam/Documents/graphql-build/packages/postgraphql-build/node_modules/graphql-build-pg/node8plus/plugins/PgQueryProceduresPlugin.js:50:53)
          at Array.reduce (native)
          at PgQueryProceduresPlugin.builder.hook (/Users/benjiegillam/Documents/graphql-build/packages/postgraphql-build/node_modules/graphql-build-pg/node8plus/plugins/PgQueryProceduresPlugin.js:23:94)
          at SchemaBuilder.applyHooks (/Users/benjiegillam/Documents/graphql-build/packages/postgraphql-build/node_modules/graphql-build/node8plus/SchemaBuilder.js:147:20)
          at fields (/Users/benjiegillam/Documents/graphql-build/packages/postgraphql-build/node_modules/graphql-build/node8plus/makeNewBuild.js:318:40)
          at resolveThunk (/Users/benjiegillam/Documents/graphql-build/node_modules/graphql/type/definition.js:169:40)
          at defineFieldMap (/Users/benjiegillam/Documents/graphql-build/node_modules/graphql/type/definition.js:350:18)
          at GraphQLObjectType.getFields (/Users/benjiegillam/Documents/graphql-build/node_modules/graphql/type/definition.js:311:44)
          at Object.newWithHooks (/Users/benjiegillam/Documents/graphql-build/packages/postgraphql-build/node_modules/graphql-build/node8plus/makeNewBuild.js:394:18)
          at QueryPlugin.builder.hook (/Users/benjiegillam/Documents/graphql-build/packages/postgraphql-build/node_modules/graphql-build/node8plus/plugins/QueryPlugin.js:23:23)
          at SchemaBuilder.applyHooks (/Users/benjiegillam/Documents/graphql-build/packages/postgraphql-build/node_modules/graphql-build/node8plus/SchemaBuilder.js:147:20)
          at Object.newWithHooks (/Users/benjiegillam/Documents/graphql-build/packages/postgraphql-build/node_modules/graphql-build/node8plus/makeNewBuild.js:176:27)
          at SchemaBuilder.buildSchema (/Users/benjiegillam/Documents/graphql-build/packages/postgraphql-build/node_modules/graphql-build/node8plus/SchemaBuilder.js:188:37)
          at Object.<anonymous>.exports.createPostGraphQLSchema (/Users/benjiegillam/Documents/graphql-build/packages/postgraphql-build/node8plus/index.js:60:18)
          at <anonymous>
          at process._tickCallback (internal/process/next_tick.js:169:7)
```
